/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteCartRouteImport } from './routes/_site.cart'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteOfferRouteImport } from './routes/_site.offer'
import { Route as SiteShopRouteImport } from './routes/_site.shop'
import { Route as SiteTermsRouteImport } from './routes/_site.terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as SiteProductIdRouteImport } from './routes/_site.product.$id'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCartRoute = SiteCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOfferRoute = SiteOfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => SiteRoute,
} as any)
const SiteShopRoute = SiteShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteProductIdRoute = SiteProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/cart': typeof SiteCartRoute
  '/contact': typeof SiteContactRoute
  '/offer': typeof SiteOfferRoute
  '/shop': typeof SiteShopRoute
  '/terms': typeof SiteTermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/product/$id': typeof SiteProductIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/cart': typeof SiteCartRoute
  '/contact': typeof SiteContactRoute
  '/offer': typeof SiteOfferRoute
  '/shop': typeof SiteShopRoute
  '/terms': typeof SiteTermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/product/$id': typeof SiteProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/cart': typeof SiteCartRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/offer': typeof SiteOfferRoute
  '/_site/shop': typeof SiteShopRoute
  '/_site/terms': typeof SiteTermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/product/$id': typeof SiteProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/offer'
    | '/shop'
    | '/terms'
    | '/admin/login'
    | '/admin/'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/cart'
    | '/contact'
    | '/offer'
    | '/shop'
    | '/terms'
    | '/admin/login'
    | '/'
    | '/admin'
    | '/product/$id'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/cart'
    | '/_site/contact'
    | '/_site/offer'
    | '/_site/shop'
    | '/_site/terms'
    | '/admin/login'
    | '/_site/'
    | '/admin/'
    | '/_site/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cart': {
      id: '/_site/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof SiteCartRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/offer': {
      id: '/_site/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof SiteOfferRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/shop': {
      id: '/_site/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof SiteShopRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/product/$id': {
      id: '/_site/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof SiteProductIdRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteCartRoute: typeof SiteCartRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteOfferRoute: typeof SiteOfferRoute
  SiteShopRoute: typeof SiteShopRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteProductIdRoute: typeof SiteProductIdRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteCartRoute: SiteCartRoute,
  SiteContactRoute: SiteContactRoute,
  SiteOfferRoute: SiteOfferRoute,
  SiteShopRoute: SiteShopRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteProductIdRoute: SiteProductIdRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
